services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres # has to match value in server/.env
      POSTGRES_PASSWORD: password # has to match value in server/.env
      POSTGRES_DB: chatapp # has to match value in server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  pgdata: